name: Checks
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  spellchecking:
    name: Spellchecking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - run: npm install yaspeller
    - run: git show -m --name-only -1 --format="format:" | grep --color=never -i '.md' | xargs node_modules/.bin/yaspeller -c .funkill/.yaspellerrc
